### ISSUE TITLE
NPM ?

### ISSUE THREAD

**Issue by DanielNasseh** [sgratzl/chartjs-chart-boxplot#101]
Hello,

is this package available via npm?

I get this when trying to install it: 

npm install chartjs-chart-boxplot

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/chartjs-chart-boxplot - Not found
npm ERR! 404
npm ERR! 404  'chartjs-chart-boxplot@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by DanielNasseh** [comment]
apologies, got it to work with: npm install chart.js @sgratzl/chartjs-chart-boxplot

**Comment by sgratzl** [comment]
see also https://github.com/sgratzl/chartjs-chart-boxplot?tab=readme-ov-file#install
