### ISSUE TITLE
Whiskers are drawn wrong

### ISSUE THREAD

**Issue by BoringBoredom** [sgratzl/chartjs-chart-boxplot#103]
version: latest, browser: Chrome
https://stackblitz.com/edit/vitejs-vite-ixmp1s?file=src%2FApp.tsx

![image](https://github.com/sgratzl/chartjs-chart-boxplot/assets/16615327/691a61c1-d06a-4aed-8bcd-a02767b9188c)

**Comment by sgratzl** [comment]
by default the whiskers extend to Q1/Q2 +/ 1.5 IQR, see also https://www.sgratzl.com/chartjs-chart-boxplot/api/interfaces/IBaseOptions.html#coef
