### ISSUE TITLE
I have no idea how to style outliers

### ISSUE THREAD

**Issue by SkyHyve** [sgratzl/chartjs-chart-boxplot#107]
There doesn't appear to be any documentation on it and I have been trying outlierColor, outlierStylem outlierRadius on the top level context, the dataset and the data but nothing seems to work

**Comment by sgratzl** [comment]
e.g. 

```
    outlierBorderColor: 'red',
    outlierBorderWidth: 4,
    outlierBackgroundColor: 'orange',
    outlierRadius: 20,
```

https://codepen.io/sgratzl/pen/MWRbowj?editors=0010
