### ISSUE TITLE
Type '"metaExtensions"' cannot be used to index type 'ChartTypeRegistry[key]'.

### ISSUE THREAD

**Issue by TearsDemon** [sgratzl/chartjs-chart-boxplot#11]
node_modules/chart.js/types/index.esm.d.ts:452:25 - error TS2536: Type '"metaExtensions"' cannot be used to index type 'ChartTypeRegistry[key]'.

As I can see, you should update `ChartTypeRegistry` and add `metaExtensions` property ([src/controllers/BoxPlotController.ts](https://github.com/sgratzl/chartjs-chart-boxplot/blob/4905cfd72c5def00b57424ba53f8aeef5ff52265/src/controllers/BoxPlotController.ts#L68))

**Comment by sgratzl** [comment]
should be fixed with https://github.com/sgratzl/chartjs-chart-boxplot/releases/tag/v3.5.0
