### ISSUE TITLE
Example website is down (https://sgratzl.com/)

### ISSUE THREAD

**Issue by bnovc** [sgratzl/chartjs-chart-boxplot#110]
Website seems to be no longer accessible: https://sgratzl.com/

**Comment by sgratzl** [comment]
the link is https://www.sgratzl.com/chartjs-chart-boxplot/

I've never figured out how to make https://sgratzl.com work only https://www.sgratzl.com

**Comment by bnovc** [comment]
Ah. Maybe update docs here:

Usage
see [Examples](https://sgratzl.com/chartjs-chart-boxplot/examples/)
