### ISSUE TITLE
Violin chart does not work when config.data.labels is empty

### ISSUE THREAD

**Issue by RudeySH** [sgratzl/chartjs-chart-boxplot#116]
I am upgrading to chart.js 4.x, and switching over from the original repo to this maintained fork.

I ran into an unexpected issue where my violin chart did not render until I added `labels: ['']` to my my config.
![image](https://github.com/sgratzl/chartjs-chart-boxplot/assets/3918757/4492f039-1875-4685-989a-89630d85c824)

In the original repo, labels was not required. As a workaround I am using an empty string at the moment.

**Comment by sgratzl** [comment]
do you need the label when you plot a normal bar chart using chart.js 4.x?

**Comment by sgratzl** [comment]
> I found that those also don't render when no labels are provided.
that would indicate that it is a chart.js core thing and thus not related to this plugin itself. Closing, please open your question in chart.js directly.
