### ISSUE TITLE
Feature request: tooltip on individual points on a box plot

### ISSUE THREAD

**Issue by mujahidfa** [sgratzl/chartjs-chart-boxplot#117]
This is a very handy library, thank you @sgratzl!

**Feature request**: It would be great if we can allow for tooltips in all individual points in the box plot and not only for the outlier.

**User story**

I would like to add further information on the individual points that are displayed via tooltip when user hovers over the specific points. So when user hovers over a point, it will know further custom context about how the point was introduced in the boxplot, and that information ideally will be displayed via a tooltip, triggered on point hover.

However, as of now, it is only possible to trigger a tooltip on hover on the outlier point only (based on #30).

<img width="284" alt="image" src="https://github.com/sgratzl/chartjs-chart-boxplot/assets/17759705/83ea5008-8f7e-4c57-a6bf-b44c616bfcfb">

Considering that it is already possible to trigger a tooltip on the outlier point, what would it take (implementation-wise on the library, not user-side) for you to enable tooltips on all individual points and not just on the outlier point? Is this something that you think is possible to further implement in this library? This would be very handy and make this library a lot more useful that can cover more use cases for boxplot visualization.

Thank you!

**Comment by sgratzl** [comment]
it might be possible but it won't scale. boxplots are designed to summarize large quantity of data points. Outliers are only a fraction of that that's why is still performant

**Comment by mujahidfa** [comment]
> it might be possible but it won't scale. boxplots are designed to summarize large quantity of data points. Outliers are only a fraction of that that's why is still performant

I see. Could we then make it optional, as in it is enabled only when the user decides to enable it? That way it doesn’t affect non-users of the feature while still allowing users the flexibility to opt-in if they choose to.

**Comment by sgratzl** [comment]
there is a new `itemHitRadius` option, if set to a value > 0 it will check for items, too
