### ISSUE TITLE
Ability to remove the whiskers

### ISSUE THREAD

**Issue by Jmeardley** [sgratzl/chartjs-chart-boxplot#119]
Is it possible to remove the whiskers from the plot? I just want the IQR to be displayed (just the box). How can I turn the whikers off? 

Also, doing a hybrid chart with multiple items on each tick of the x axis. The boxplots arrange next to each other on each tick nicely, but I am unable to get a bubble, which i am using as a reference point for the current data to lineup on top of the boxplot connected to it. Is there a way to do this?

**Comment by Jmeardley** [comment]
i was able to remove the whiskers and the outliers, but I cant find a way to add a reference point that lines up with each boxplot

**Comment by sgratzl** [comment]
if you are just using a box, have you thought of using using a bar chart that has a bar not starting at 0?
