### ISSUE TITLE
Type improvements for `IBoxPlot` and other interfaces

### ISSUE THREAD

**Issue by fnimick** [sgratzl/chartjs-chart-boxplot#120]
Currently, `IBoxPlot` and the other data interfaces requires all members to be defined.

This results in e.g.
```ts
  let data = {
    min: 1,
    q1: 2,
    median: 3,
    q3: 4,
    max: 5,
  } satisfies IBoxPlot;
```
having a compile error due to the missing `whiskerMax, whiskerMin, mean, items, outliers` members - even though it works fine at runtime.

It would be great if there were well-defined object types that could be used to strongly type the data input, with members appropriately marked as optional.

**Comment by sgratzl** [comment]
have you tried using https://www.sgratzl.com/chartjs-chart-boxplot/api/type-aliases/BoxPlotDataPoint.html instead?
