### ISSUE TITLE
Scale issue

### ISSUE THREAD

**Issue by aspirew** [sgratzl/chartjs-chart-boxplot#122]
I cannot scale chart properly for following configuration:

```
    const chartConfig: ChartConfiguration<"boxplot"> = {
        type: 'boxplot',
        data: {
            labels: ["column"],
            datasets: [
                {
                    label: "labels",
                    data: [[1,2,3], [3,4,1], []],
                    borderColor: colors[0],
                    backgroundColor: colors[0],
                }
            ]
        },
        options: {
            minStats: 'whiskerMin',
            maxStats: 'whiskerMax',    
        }
    };
```

I expect chart to start at 1 and end on 3. Looks like it remains with default configuration:

![image](https://github.com/sgratzl/chartjs-chart-boxplot/assets/41696945/040310a3-5a3e-4cb8-8429-464f1bdd8022)

**Comment by sgratzl** [comment]
I think two things are happening here
 * chart.js has by default that the scale starts with 0
 * the scale itself is influenced by all the data (all 3) not just the one which has a label

e.g.
```js
window.onload = () => {
  const ctx = document.getElementById("canvas").getContext("2d");
    new Chart(ctx, {
        type: 'boxplot',
        data: {
            labels: ["column"],
            datasets: [
                {
                    label: "labels",
                    data: [[1,2,3,3,3,3, 10]],
                }
            ]
        },
        options: {
            minStats: 'whiskerMin',
            maxStats: 'whiskerMax',
            scales: {
              y: {
                beginAtZero: false
              }
            }
        },
    });

};
```

results in 

![image](https://github.com/sgratzl/chartjs-chart-boxplot/assets/4129778/3c80b7c2-ac83-4c8a-ba5b-7ed310948a12)

**Comment by aspirew** [comment]
Yes, it affects all the data so you need to keep an eye on that. It also didnt work for me without 'beginAtZero' property, looks much better now. Thank you, great project :)
