### ISSUE TITLE
Adding data points for reference

### ISSUE THREAD

**Issue by beriknl** [sgratzl/chartjs-chart-boxplot#15]
First of all, thanks for this awesome plugin!

I have been able to generate the boxplot with the default values, mix/q2/median/q3/max. 

For my exercise, I would however like to add some additional data points for reference purpose. How would I go about this? 

As shown in the image on the repository, 
https://user-images.githubusercontent.com/4129778/42724341-9a6ec554-8770-11e8-99b5-626e34dafdb3.png
It shows additional fields as well. 

I would like to show, for example, the value "Previous" as a unique value on the plot/chart. Would you have any advice how to go about this?

**Comment by sgratzl** [comment]
you can customize the `itemRadius` to enable rendering of all items, see also https://github.com/sgratzl/chartjs-chart-boxplot/blob/2fdbbdfa607a98c090c2e7a18dbf6e7438191627/samples/items.html#L28
