### ISSUE TITLE
Highlight the specific point on box-plot

### ISSUE THREAD

**Issue by deviirmr** [sgratzl/chartjs-chart-boxplot#16]
I like your library very much and it's exactly what  I am looking for...
Using you lib I have created a chart with 100 data points that represent the score from the different users.
Now I wish to highlight the score of the specific user so that he can recognize his status on the box plot.
is it possible to highlight the specific point of one user in the box-plot, such as with different colours or Size?

I tried something inside datasets, but it's not working

```
        itemRadius: function(context) {

              context.raw.forEach((val) => {
                   if(val == 5) {
                   console.log(val);
                   return 5;

                   }
                   else {
                    console.log(val);
                   return 20;
                   }
                   });

                }
```

I am using version 3.6.0

Do you have any suggestions?

Thanks!

**Comment by sgratzl** [comment]
This is currently not possible since individual items points are just addons to the boxplots but not visual points by themselves.

**Comment by 676339784** [comment]
@sgratzl Have a similar question, let me know if I should create a separate issue

I want to have a tooltip when hovering over the individual items points, is that possible? I can do it with outliers but not the non-outlier ones

**Comment by sgratzl** [comment]
that is also not possible mainly because of scalability reasons. box plots are usually used when you have a lot of data points, thus computing the overlap would be expensive
