### ISSUE TITLE
Remove points from the box plot

### ISSUE THREAD

**Issue by Seojunhyeong2003** [sgratzl/chartjs-chart-boxplot#168]
Hi, I was wondering how to remove the dot in the middle of the boxplot chart.

I want the form where the middle point is removed as shown in the screenshot below.

<img width="59" alt="스크린샷 2024-10-10 오후 4 57 04" src="https://github.com/user-attachments/assets/e193857b-5419-4940-8366-4ed2c41617c2">

I would like to know how I can apply it in the codepen link below.

https://codepen.io/sgratzl/pen/QxoLoY

**Comment by sgratzl** [comment]
try setting `meanRadius` to 0

https://github.com/sgratzl/chartjs-chart-boxplot/blob/fca4aabef09c63caa03bc29f5c51fb936b8f1637/src/elements/base.ts#L159-L165

**Comment by Seojunhyeong2003** [comment]
Thank you very much. You are the god of development
