### ISSUE TITLE
Maximum not always showing up correct in boxplot

### ISSUE THREAD

**Issue by phrei** [sgratzl/chartjs-chart-boxplot#181]
In your [Code-Pen](https://codepen.io/sgratzl/pen/QxoLoY) I've changed the data to:

```
const boxplotData = {
  // define label tree
  labels: ["January", "February"],
  datasets: [
    {
      label: "Dataset 1",
      backgroundColor: "rgba(255,0,0,0.5)",
      borderColor: "red",
      borderWidth: 1,
      outlierColor: "#999999",
      padding: 10,
      itemRadius: 0,
      data: [
        {
          min: 1,
          q1: 2,
          median: 3,
          q3: 5.75,
          max: 15
        },
        {
          min: 1,
          q1: 2,
          median: 3,
          q3: 5.75,
          max: 8
        }
      ]
    }
  ]
};
```

**The outcome:** The right chart seems to have the correct bounds, the left chart stops under 12 (although the Maximum is set to 15). After some threshold the chart seems to see an "outlier". The Tooltip is correct though.

I expect the upper line to be at 15.

**Comment by sgratzl** [comment]
this is the expected default behavior. The whisker extend by default to +/- 1.5 * IQR

see also

https://github.com/sgratzl/chartjs-chart-boxplot/blob/220e2d7b3de91a73dfd9ca8cb8d5247682703769/src/data.ts#L116-L123

**Comment by phrei** [comment]
Thank you for clarifying and responding so quickly!
