### ISSUE TITLE
How to Customize Boxplot Tooltip for Outliers and Time Units?

### ISSUE THREAD

**Issue by mariachi0630** [sgratzl/chartjs-chart-boxplot#182]
Hello! I am using the @sgratzl/chartjs-chart-boxplot plugin to implement a boxplot.

Questions:

1. When hovering over an outlier in the boxplot, I would like to display both the index of the corresponding row and the value of the outlier in the tooltip. Is there a way to achieve this?
<img width="506" alt="NO INDEX" src="https://github.com/user-attachments/assets/07503f8a-5a81-4118-b1ad-a9c818a2342c">

2. Is it possible to modify the summary statistics displayed when hovering over the box plot (e.g., min, max, median) to display time units (e.g., 1h 23m 06s)? If yes, could you please guide me on how to implement this?

Thank you in advance for your help!

**Comment by sgratzl** [comment]
take a look at how chart.js supports customizing the tooltip. In addition, this plugin injects additional data for outliers tooltips in the data model:

https://github.com/sgratzl/chartjs-chart-boxplot/blob/f9f20dad666f1ceac89bccffe38908fdfb9a9146/src/tooltip.ts#L3C18-L12
