### ISSUE TITLE
Provide summary data

### ISSUE THREAD

**Issue by JeremyBradshaw7** [sgratzl/chartjs-chart-boxplot#20]
I'd like to have the plugin work with the summary data I give it (eg. whisker values, mean & quartiles), rather than working out the summary from a set of points. I think you refer to this in your readme but the link provided (https://github.com/sgratzl/chartjs-chart-boxplot/blog/dev/src/data.ts#L24-L49) is dead. Can you provide some detail how to do it, or fix the link?

Can this plugin be used for chartjs v2 or is it only for v3?

**Comment by JeremyBradshaw7** [comment]
I think I found out from the code, so it's something like:

```
    data: [
      {min: 5, q1: 40, median: 50, mean: 55, q3: 60, max: 95},
    ]
```

`mean` can be omitted but `median` cannot it seems.

**Comment by sgratzl** [comment]
see also https://github.com/sgratzl/chartjs-chart-boxplot/blob/main/samples/datastructures.html

**Comment by JeremyBradshaw7** [comment]
Thanks
