### ISSUE TITLE
Configure colours

### ISSUE THREAD

**Issue by JeremyBradshaw7** [sgratzl/chartjs-chart-boxplot#21]
It would be great if you could configure the colours for above and below the median separately, or all elements of the box (whiskers etc).

**Comment by sgratzl** [comment]
see also 
https://github.com/sgratzl/chartjs-chart-boxplot/blob/388c3383907f1e10c2ad4385a0ac63982f22ff99/src/elements/base.ts#L6  
and 
https://github.com/sgratzl/chartjs-chart-boxplot/blob/388c3383907f1e10c2ad4385a0ac63982f22ff99/src/elements/BoxAndWiskers.ts#L6

**Comment by JeremyBradshaw7** [comment]
Thanks - the docs could do with an update to make this clearer.

**Comment by sgratzl** [comment]
> Thanks - the docs could do with an update to make this clearer.
I'm looking forward to your PR
