### ISSUE TITLE
Making a Boxplot Chart with precomputed values.

### ISSUE THREAD

**Issue by skildfrix** [sgratzl/chartjs-chart-boxplot#22]
Hi. I made a basic boxplot chart on my web application based on the docs. By default, this plugin accepts an array of data being stored on the dataset. Do you have examples on how it accepts precomputed values (for the minimum, maximum, median, outliers) instead of processing everything on the client side?

I'm planning to compute the min, max, median etc... to the server side instead to make my application run a little bit faster. I am working on hundred thousands of data and passing over the individual data from the server to client is a very slow. I would appreciate you answer.

Thanks! :)

**Comment by sgratzl** [comment]
see also https://github.com/sgratzl/chartjs-chart-boxplot/blob/main/samples/datastructures.html

**Comment by skildfrix** [comment]
> see also https://github.com/sgratzl/chartjs-chart-boxplot/blob/main/samples/datastructures.html

Awesome! Thanks! 👍
