### ISSUE TITLE
Is it possible to ignore outliers?

### ISSUE THREAD

**Issue by jasondilworth56** [sgratzl/chartjs-chart-boxplot#27]
I'd like to draw some boxplots without the outliers. Is this something that is possible?

**Comment by sgratzl** [comment]
have you tried setting `outlierRadius` to 0?

https://github.com/sgratzl/chartjs-chart-boxplot/blob/32fa5cf93c006b7afd6c09ac68061c540db49d1c/src/elements/base.ts#L50
