### ISSUE TITLE
Is it possible to get a tooltip on individual points on a box plot? 

### ISSUE THREAD

**Issue by gisheri** [sgratzl/chartjs-chart-boxplot#30]
I would like to show a tooltip for each point in a horizontal box plot

The outlier points get their own tooltip, but I can only seem to trigger a tooltip for the entire box area for any non-outliers. The tooltip item in the callbacks and filters doesn't help, because item in the argument only refers to the entire box as well, so i can't seem to narrow it down there. I've tried setting the interaction mode to point, but it doesn't seem to change this functionality. 

https://user-images.githubusercontent.com/4277439/168725257-300d939f-9f45-4703-a632-351c316282ff.mov

I'm on 3.7.2
 
Thanks

**Comment by sgratzl** [comment]
this plugin doesn't support tooltips on individual points. On outliers (i.e. the grey point on the left), they should automatically appear.

**Comment by Andrewg1263** [comment]
I am not sure if combing scatter plot and box plot is the correct way to do,
but it seems working for showing tooltip for a single point.

```  javascript
const boxplotData = {
  // define label tree
  labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
  datasets: [{
    label: 'Dataset 1',
    backgroundColor: 'rgba(255,0,0,0.5)',
    borderColor: 'red',
    borderWidth: 1,
    outlierColor: '#999999',
    padding: 10,
    itemRadius: 0,
    order: 2,
    data: [
      randomValues(100, 0, 100),
      randomValues(100, 0, 20),
      randomValues(100, 20, 70),
      randomValues(100, 60, 100),
      randomValues(40, 50, 100),
      randomValues(100, 60, 120),
      randomValues(100, 80, 100)
    ]
  },{
    type: 'scatter',
    label: 'Scatter Dataset',
    borderColor: 'rgb(75, 192, 192)',
    data:[{
      x: 'January',
      y: 20
    }, {
      x: 'January',
      y: 40
    }],
    order:1,
  }]
};
```

Reference: 
https://www.chartjs.org/docs/latest/charts/mixed.html
https://codepen.io/sgratzl/pen/QxoLoY
