### ISSUE TITLE
Tooltips `custom` doesn't work

### ISSUE THREAD

**Issue by roman-golubov** [sgratzl/chartjs-chart-boxplot#34]
I'm having the following question...
After moving from [@datavisyn/chartjs-chart-box-and-violin-plot](https://github.com/datavisyn/chartjs-chart-box-and-violin-plot)
Tooltips doesn't work. We are using custom function for tooltips render.

**Correct result before update was this**
![p7ks5zwim7tw8909wfyxl5w1vcaeo3](https://user-images.githubusercontent.com/10779650/179504473-6bc37ce0-88c6-4c8f-bc77-054420262589.jpg)

**Screenshots / Sketches**
![Screenshot 2022-07-18 at 14 44 09](https://user-images.githubusercontent.com/10779650/179504258-06733c26-f8d2-413a-a9fd-d6a346df4f98.jpg)

**Comment by sgratzl** [comment]
can you provide an example containing the following:
 * a *bar chart* in which the custom tooltip work - to avoid that it due to the chart.js 3 upgrade
 * a boxplot version using the same custom tooltip in which it doesn't work

**Comment by roman-golubov** [comment]
I'm using Vue js.
The solution was to import chart js plugin via Tree shaking

``` javascript
import { Chart, Tooltip, CategoryScale, LinearScale } from 'chart.js';
import { BoxPlotChart } from '@sgratzl/chartjs-chart-boxplot';
Chart.register(
  BoxPlotChart,
  Tooltip,
  CategoryScale,
  LinearScale
);
```
