### ISSUE TITLE
Library Not compatible with ivy - angular version 14

### ISSUE THREAD

**Issue by Ram7221** [sgratzl/chartjs-chart-boxplot#49]
This likely means that the library (@sgratzl/chartjs-chart-boxplot) which declares BoxPlotChart has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

this is the issue i am facing while after installing @sgratzl/chartjs-chart-boxplot

**Comment by sgratzl** [comment]
can you provide an example where I can test it?

**Comment by Ram7221** [comment]
@sgratzl I wanted to use this boxplot chart in angular project version 14 , when i installed the chart package and tried to start the program , i am facing this issue

**Comment by sgratzl** [comment]
closing and no example provided
