### ISSUE TITLE
Why does it say "NaN" instead of numbers in the list of min, max, 25%, 50%, 75% ??

### ISSUE THREAD

**Issue by IwanHB** [sgratzl/chartjs-chart-boxplot#5]
Hi there. 
Thanks for all your great work.

In the sample given as an example;
[https://codepen.io/sgratzl/pen/QxoLoY](https://codepen.io/sgratzl/pen/QxoLoY)
when I mouseover the boxplots, instead of giving the values for the mean, min, max, 25%, 50% and 75% is says "NaN".

[https://prnt.sc/13oo9kf](https://prnt.sc/13oo9kf)

Why is that?

**Comment by sgratzl** [comment]
cannot reproduce:

![image](https://user-images.githubusercontent.com/4129778/122278898-b981f080-cee7-11eb-9e95-8cb422e9fe5f.png)
