### ISSUE TITLE
Trying to use this with vue-chartjs

### ISSUE THREAD

**Issue by mathijsfr** [sgratzl/chartjs-chart-boxplot#6]
I am trying to use this package with `vue-chartjs: 3.5.1`, `chartjs: 2.9.4`, and `vue: 2.6.12`, but I am getting the the following error:

./node_modules/@sgratzl/chartjs-chart-boxplot/build/index.umd.js
Module not found: Error: Can't resolve 'chart.js/helpers' in 'D:\-\src\webapp\vue_frontend\node_modules\@sgratzl\chartjs-chart-boxplot\build'

My BoxPlot.js looks like this:

```
import { mixins } from "vue-chartjs";
import { BoxPlotChart } from '@sgratzl/chartjs-chart-boxplot';


export default {
  name: 'box-plot',
  extends: BoxPlotChart,
  mixins: [mixins.reactiveProp],
  props: {
    options: Object,
  },
  mounted() {
    this.renderChart(this.chartData, this.options);
  }
};
```

Other parts of the code is taken from the following example:
https://github.com/sgratzl/vue-chartjs-boxplot

The reason I am trying to use this package instead of chartjs-chart-box-and-violin-plot, is because with my versions of vue, chartjs and vue-chartjs it seems that the boxplot doesn't update properly. It sometimes works on refresh and sometimes not.

Is there something I can do to make this package work with vue?

**Comment by sgratzl** [comment]
the latest version of this plugin is just compatible with chart.js 3 that's why you cannot find the chart.js/helpers module
