### ISSUE TITLE
Boxplot not working properly

### ISSUE THREAD

**Issue by xde013** [sgratzl/chartjs-chart-boxplot#7]
Chart type boxplot doesn't seem to behave as expected:
  - No tooltips appear
  - Chart is plotted only in first x column (dataset mapping issue?)

**To Reproduce**
Please refer to this demo -> https://codesandbox.io/s/interesting-haze-i0421

**Additional context**

- react
- chartjs
- react-chartjs-2
-----------------------------------------------------------------------------------------------
 🚩 Chart behaving normally when setting chart option `indexAxis` to `'y'`.

**Comment by sgratzl** [comment]
there seems to be some incompatibilities with chart.js 3.4.x if you go back to 3.3 it works as expected.

**Comment by TearsDemon** [comment]
As I can see problem in this code on Chart.js: https://github.com/chartjs/Chart.js/pull/9208

**Comment by sgratzl** [comment]
should be fixed with https://github.com/sgratzl/chartjs-chart-boxplot/releases/tag/v3.5.0
