### ISSUE TITLE
boxplot displaying the min/max as top and bottom whiskers

### ISSUE THREAD

**Issue by ftiercelin** [sgratzl/chartjs-chart-boxplot#70]
Hello,

First of all, many thanks for this very useful library.

I thought the top and bottom whiskers of a box plot would represent the max/min values. It seems that by default, boxplots are using the IQR to define the top/bottom whiskers.
e.g. with these 2 populations:
- {min: 50,q1: 70,median: 80,mean: 82,q3: 90,max: 150,}
- {min: 50,q1: 75,median: 80,mean: 82,q3: 85,max: 150,}

where population 1 has an IQR of 20 versus an IQR of 10 for population 2 but all other values being identical.
I'm getting the following graph:
![image](https://github.com/sgratzl/chartjs-chart-boxplot/assets/22170293/fb3bb8f5-e495-4608-945e-85e104423f77)

I understand the benefits of using the IQR to define the top/bottom whiskers, but is there a way to not use the IQR and just use the min/max, no matter what they are?

chart.js@4.3.0
chartjs-chart-boxplot@4.2.0

**Comment by sgratzl** [comment]
see https://github.com/sgratzl/chartjs-chart-boxplot/blob/ecf744254bcabcbd137f3b7cc4aea2aec41d07d5/src/data.ts#L104-L137

**Comment by ftiercelin** [comment]
Thanks!
