### ISSUE TITLE
Cannot register BoxAndWhiskers

### ISSUE THREAD

**Issue by camer314** [sgratzl/chartjs-chart-boxplot#75]
I am using the current version of your library (4.2.2) and chart.js (4.3.0)

During Chart.Register(BoxAndWiskers) it fails with the error:

Argument of type 'typeof BoxAndWiskers' is not assignable to parameter of type 'ChartComponentLike'.
  Type 'typeof BoxAndWiskers' is not assignable to type '{ [key: string]: ChartComponent; }'.
    Index signature for type 'string' is missing in type 'typeof BoxAndWiskers'

**Comment by sgratzl** [comment]
should be fixed with the new patch release
