### ISSUE TITLE
Option usage

### ISSUE THREAD

**Issue by T3chTobi** [sgratzl/chartjs-chart-boxplot#87]
Hello, I'm using the boxplot in Vanilla JS with the following code:

```js
<script src="https://unpkg.com/chart.js@4"></script>
<script src="https://unpkg.com/@sgratzl/chartjs-chart-boxplot@4"></script>
<script>

    const boxplotData = {
        // define label tree
        labels: ['January'],
        datasets: [{
            label: 'Dataset 1',
            backgroundColor: 'rgba(255,0,0,0.5)',
            borderColor: 'red',
            borderWidth: 1,
            outlierColor: '#999999',
            padding: 10,
            itemRadius: 0,
            data: [
                [...]
            ],
            legend: {
                position: 'bottom',
            },
        }]
    };
    window.onload = () => {
        const ctx = document.getElementById("canvas").getContext("2d");
        window.myBar = new Chart(ctx, {
            type: 'boxplot',
            data: boxplotData,
            options: {
                indexAxis: 'y',
                responsive: true,
                legend: {
                    display: false,
                    position: 'top',
                },
                title: {
                    display: false,
                    text: 'Chart.js Box Plot Chart'
                },
            }
        });

    };

</script>
```
This is how it looks on the website:
<img width="764" alt="Screenshot 2023-10-10 at 03 38 28" src="https://github.com/sgratzl/chartjs-chart-boxplot/assets/7794412/0933e6ea-8aa5-44f1-804d-e4976eff9aa5">

I would like to do the following things and tried the options inside the documentation, but it did not work:
- Hide `Dataset 1` and `January`
- Set a custom `height` and `width` for the canvas (it currently looks stretched out...)

How can I do that? The only parameter from `options` that seems to work is the `indexAxis` which works as intended. The other parameters don't work. I did not find parameters to set a custom height and width of the canvas.

**Comment by lukaszahorec** [comment]
Same here, I am using violin and also box plot and options.legend.display: false seem not to work, legend is still showing.

**Comment by sgratzl** [comment]
this seems overall a chart.js question than a this plugin specific question. This plugin doesn't render the legend or title
