### ISSUE TITLE
How to plot split violin plot ?

### ISSUE THREAD

**Issue by chilin0525** [sgratzl/chartjs-chart-boxplot#93]
Hi, I searching the lightweight tool to plot split violin, just like following screenshot  in [seaborn](https://github.com/mwaskom/seaborn) python package. Does this repo support to plot split violin now?

**Screenshots / Sketches**

The screenshot is from [stackoverflow](https://stackoverflow.com/questions/58164531/seaborn-violin-plot-compare-all-to-one)

![image](https://github.com/sgratzl/chartjs-chart-boxplot/assets/41913261/ca437707-8093-4386-823c-c7d796a37c86)

**Context**

- Version: 4.2.7
- Browser: Edge

**Additional context**

None.

**Comment by sgratzl** [comment]
that is currently not possible with this plugin

**Comment by chilin0525** [comment]
ok, thank your. 👍
