### ISSUE TITLE
Controlling the width / thickness of the boxplot

### ISSUE THREAD

**Issue by ajyang818** [sgratzl/chartjs-chart-boxplot#94]
Is it possible to control how "thick" the boxplot is, ie its width?

Here's a screenshot of what I have so far:
![image](https://github.com/sgratzl/chartjs-chart-boxplot/assets/2760000/6de177f3-8190-47d1-af3c-69cee9aa3798)

This is a horizontal boxplot, so what I'm trying to reduce is how 'tall' the box is in the vertical direction. 

Here's a Codepen that's pretty close to what I'm doing right now: https://codepen.io/Allen-Yang-the-reactor/pen/poGOpxW

**Comment by sgratzl** [comment]
you should be able to use the same properties as when changing the width of a categorical scale in chart.js, e.g. https://www.chartjs.org/docs/latest/charts/bar.html#barthickness

**Comment by ajyang818** [comment]
That does it - thanks!
